name: CI for GO server
on: 
  push: 
    branches:
    - master
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - name: Step 1 Checkout repo
      uses: actions/checkout@v2
    - name: Step 2 Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Step 3 Setup Dependencies    
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/gorilla/mux
    - name: Step 4 Build
      run: go build .
    - name: Step 5 Use Linter
      run: |
        go vet .
        golint .  

      # You can't use the - symbol for name, run and uses fielda on the same step. Only one - for the whole step. Here for example you have it for multiple name and run fields for the same step.